 #Colors (Gruvbox dark)
#colors:
   #Default colors
  #primary:
     #hard contrast: background = '0x1d2021'
    #background: '0x282828'
     #soft contrast: background = '0x32302f'
    #foreground: '0xebdbb2'

   #Normal colors
  #normal:
    #black:   '0x282828'
    #red:     '0xcc241d'
    #green:   '0x98971a'
    #yellow:  '0xd79921'
    #blue:    '0x458588'
    #magenta: '0xb16286'
    #cyan:    '0x689d6a'
    #white:   '0xa89984'

   #Bright colors
  #bright:
    #black:   '0x928374'
    #red:     '0xfb4934'
    #green:   '0xb8bb26'
    #yellow:  '0xfabd2f'
    #blue:    '0x83a598'
    #magenta: '0xd3869b'
    #cyan:    '0x8ec07c'
    #white:   '0xebdbb2'

colors:
  primary:
    background: '#2e3440'
    foreground: '#d8dee9'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  selection:
    background: '#4c566a'
  search:
    matches:
      background: '#88c0d0'
    bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'

font:
  # The size to use.
  size: 14
  # The normal (roman) font face to use.
  normal:
    family: Hack Nerd Font 
    # Style can be specified to pick a specific face.
    #style: Regular

  # The bold font face
  bold:
    family: Hack Nerd Font 
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: Hack Nerd Font 
    # Style can be specified to pick a specific face.
    # style: Italic   white:   '0xebdbb2'
